#!/usr/bin/python3
from sys import argv

with open(argv[1]) as f:
    for line in f:
        num = int(line)
        print("{:d}=".format(num), end="")
        if num % 2 == 0:
            print("{}*2".format(num//2))
            continue
        for i in range(3, num, 2):
            if num % i == 0:
                factor = num//i
                for j in range(3, factor, 2):
                    if factor % j == 0 or i % j == 0:
                        break
                print("{}*{}".format(factor, i))
                break
def prime_factors(n):
    factors = []
    # Divide by 2 as many times as possible
    while n % 2 == 0:
        factors.append(2)
        n //= 2
    # Divide by odd numbers until n is reduced to 1
    for i in range(3, int(n ** 0.5) + 1, 2):
        while n % i == 0:
            factors.append(i)
            n //= i
    # Add the remaining factor if it is greater than 2
    if n > 2:
        factors.append(n)
    return factors


# Check if a file was provided as an argument
if len(sys.argv) != 2:
    print("Usage: factors <file>")
    sys.exit(1)

# Read the file and factorize each number
with open(sys.argv[1], "r") as f:
    for line in f:
        n = int(line.strip())
        factors = prime_factors(n)
        print(f"{n}=", end="")
        print("*".join(str(f) for f in factors))

