#!/usr/bin/env bash
check_factor() {
    if [ $# -ge 3 ]; then
        num2=$3
    else
        num2=$(echo "$1" | cut -d':' -f2)
    fi

    num1=$2

    if ((num2 > num1)); then
        temp=$num1
        num1=$num2
        num2=$temp
    fi

    echo "$1=$num1*$num2"
}

if [ $# -ne 1 ]; then
    echo 'Usage: rsa <file>'
    exit 1
else
    while read i; do
        result=$(factor "$i")
        check_factor "$result"
    done < "$1"
fi
if [ $# -ne 1 ]
then
        echo 'Usage: rsa <file>'
        exit 1
else

        while read i
        do

                result=$(factor "$i")
                check_factor $result

        done < "$1"
fi
