#!/usr/bin/python3
import sys

def factorization():
    """
    Factorize RSA numbers. For each RSA number n, find prime numbers p and q such that n = p × q.
    """
    try:
        files = sys.argv[1]
        with open(files) as f:
            for number in f:
                number = int(number)
                if number % 2 == 0:
                    print("{}={}*{}".format(number, number // 2, 2))
                    continue
                divisor = 3
                while divisor <= number // 2:
                    if number % divisor == 0:
                        print("{}={}*{}".format(number, number // divisor, divisor))
                        break
                    divisor += 2
                if divisor > (number // 2):
                    print("{}={}*{}".format(number, number, 1))
    except IndexError:
        print("Usage: {} <file>".format(sys.argv[0]))

factorization()
